### ISSUE TITLE
Models does not resolve in RailwayApp

### ISSUE THREAD

**Issue by lomithrani** [lomithrani/portfolio#28]
As server files are not included we get 

```

#12 2.407 Could not resolve "../../../../Server/models" from "src/routes/hire/+page.svelte"

#12 2.407 file: /app/src/routes/hire/+page.svelte

#12 2.410 error during build:

#12 2.410 RollupError: Could not resolve "../../../../Server/models" from "src/routes/hire/+page.svelte"

#12 2.410     at error (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)

 

#12 2.410     at ModuleLoader.handleInvalidResolvedId (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:24860:24)

#12 2.410     at file:///app/node_modules/rollup/dist/es/shared/node-entry.js:24822:26

#12 2.425 error: script "build" exited with code 1 (SIGHUP)
```

Full logs:
```
[Region: us-west1]

==============

Using Nixpacks

==============


context: 4c35de17a81c0328b43b0d320f27f316

 

╔════════════════════ Nixpacks v1.17.0 ════════════════════╗

║ setup      │ nodejs_18, bun                              ║

║──────────────────────────────────────────────────────────║

║ install    │ bun i --no-save                             ║

║──────────────────────────────────────────────────────────║

║ build      │ bun run build                               ║

║──────────────────────────────────────────────────────────║

║ start      │ PORT=${PORT:-4000} bun --bun build/index.js ║

╚══════════════════════════════════════════════════════════╝

 

 

#0 building with "default" instance using docker driver

 

#1 [internal] load .dockerignore

#1 transferring context: 2B done

 

#1 DONE 0.0s

 

#2 [internal] load build definition from Dockerfile

#2 transferring dockerfile: 2.52kB done

#2 DONE 0.0s

 

#3 [internal] load metadata for ghcr.io/railwayapp/nixpacks:ubuntu-1695686596

 

#3 DONE 0.3s

 

 

#4 [stage-0  1/10] FROM ghcr.io/railwayapp/nixpacks:ubuntu-1695686596@sha256:863c9103f1ec289f4d8d56a656945c673b2d580080b96738e966e52e49463387

 

#4 DONE 0.0s

 

#5 [internal] load build context

#5 transferring context: 768.29kB done

#5 DONE 0.0s

 

#6 [stage-0  2/10] WORKDIR /app/

#6 CACHED

 

#7 [stage-0  3/10] COPY .nixpacks/nixpkgs-5148520bfab61f99fd25fb9ff7bfbb50dad3c9db.nix .nixpacks/nixpkgs-5148520bfab61f99fd25fb9ff7bfbb50dad3c9db.nix

#7 CACHED

 

#8 [stage-0  4/10] RUN nix-env -if .nixpacks/nixpkgs-5148520bfab61f99fd25fb9ff7bfbb50dad3c9db.nix && nix-collect-garbage -d

#8 CACHED

 

#9 [stage-0  5/10] COPY . /app/.

#9 DONE 0.0s

 

#10 [stage-0  6/10] RUN --mount=type=cache,id=s/db3d1d13-0016-4a56-a8b1-f33e6c3395e4-/root/bun,target=/root/.bun bun i --no-save

 

#10 0.379 bun install v1.0.2 (37edd5a6)

 

#10 1.472  + @fontsource/fira-mono@4.5.10

#10 1.472  + @neoconfetti/svelte@1.0.0

#10 1.472  + @playwright/test@1.38.1

#10 1.472  + @sveltejs/adapter-auto@2.1.0

#10 1.472  + @sveltejs/kit@1.25.1

#10 1.472  + @types/cookie@0.5.2

#10 1.472  + @types/google.accounts@0.0.10
#10 1.472  + @typescript-eslint/eslint-plugin@6.7.4

#10 1.472  + @typescript-eslint/parser@6.7.4

#10 1.472  + elysia@0.7.15

 

#10 1.472  + eslint@8.50.0

#10 1.472  + eslint-config-prettier@8.10.0

#10 1.472  + eslint-plugin-svelte@2.33.2

#10 1.472  + prettier@2.8.8

#10 1.472  + prettier-plugin-svelte@2.10.1

#10 1.473  + svelte@4.2.1

#10 1.473  + svelte-adapter-bun@0.5.0

#10 1.473  + svelte-check@3.5.2

#10 1.473  + tslib@2.6.2

#10 1.473  + typescript@5.2.2

#10 1.473  + vite@4.4.10

#10 1.473  + vitest@0.32.4

#10 1.473  + @elysiajs/eden@0.7.4

#10 1.473

#10 1.473  275 packages installed [1106.00ms]

 

#10 DONE 1.7s

 

 

#11 [stage-0  7/10] COPY . /app/.

#11 DONE 0.0s

 

#12 [stage-0  8/10] RUN --mount=type=cache,id=s/db3d1d13-0016-4a56-a8b1-f33e6c3395e4-node_modules/cache,target=/app/node_modules/.cache bun run build

 

#12 0.365 $ vite build

 

#12 0.735 ▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]

#12 0.735

#12 0.735     tsconfig.json:2:12:

#12 0.735       2 │   "extends": "./.svelte-kit/tsconfig.json",

#12 0.735         ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#12 0.735

 

#12 1.880

#12 1.880 vite v4.4.10 building SSR bundle for production...

#12 1.926 transforming...

 

#12 2.407 ✓ 38 modules transformed.

#12 2.407 ✓ built in 524ms

#12 2.407 Could not resolve "../../../../Server/models" from "src/routes/hire/+page.svelte"

#12 2.407 file: /app/src/routes/hire/+page.svelte

#12 2.410 error during build:

#12 2.410 RollupError: Could not resolve "../../../../Server/models" from "src/routes/hire/+page.svelte"

#12 2.410     at error (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)

 

#12 2.410     at ModuleLoader.handleInvalidResolvedId (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:24860:24)

#12 2.410     at file:///app/node_modules/rollup/dist/es/shared/node-entry.js:24822:26

#12 2.425 error: script "build" exited with code 1 (SIGHUP)

 

#12 ERROR: process "/bin/bash -ol pipefail -c bun run build" did not complete successfully: exit code: 1

-----

> [stage-0  8/10] RUN --mount=type=cache,id=s/db3d1d13-0016-4a56-a8b1-f33e6c3395e4-node_modules/cache,target=/app/node_modules/.cache bun run build:

2.407 ✓ 38 modules transformed.

2.407 ✓ built in 524ms

2.407 Could not resolve "../../../../Server/models" from "src/routes/hire/+page.svelte"

2.407 file: /app/src/routes/hire/+page.svelte

2.410 error during build:

2.410 RollupError: Could not resolve "../../../../Server/models" from "src/routes/hire/+page.svelte"

2.410     at error (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)

2.410     at ModuleLoader.handleInvalidResolvedId (file:///app/node_modules/rollup/dist/es/shared/node-entry.js:24860:24)

2.410     at file:///app/node_modules/rollup/dist/es/shared/node-entry.js:24822:26

 

2.425 error: script "build" exited with code 1 (SIGHUP)

-----

Dockerfile:24

-------------------

22 |     # build phase

23 |     COPY . /app/.

24 | >>> RUN --mount=type=cache,id=s/db3d1d13-0016-4a56-a8b1-f33e6c3395e4-node_modules/cache,target=/app/node_modules/.cache bun run build

25 |

26 |

-------------------

ERROR: failed to solve: process "/bin/bash -ol pipefail -c bun run build" did not complete successfully: exit code: 1

 

Error: Docker build failed

 
```

**Comment by lomithrani** [comment]
fixed by #29
